---
title: Hello Vincent's VuePress
description: Just playing around

base: /vuepress/

markdown:
  lineNumbers: true

themeConfig:
  sidebar:
    - '/'
    - '/test'
  sidebarDepth: 2
  displayAllHeaders: true
