---
title: Hello Vincent's VuePress
description: Just playing around

base: /vuepress/

markdown:
  lineNumbers: true

themeConfig:
  nav:
    - text: 'Home'
      link: '/'
    - text: 'Repo'
      link: 'https://github.com/vincentliu99999/vuepress'
  sidebar:
    # - '/'
    # - 
    #   - '/test'
    #   - 'test page'
    - title: '入門'
      children:
        - '/guide/'
        - '/guide/quick-start'
        - '/guide/config'
        - '/guide/markdown'
        - '/guide/deploy'
        # - '/vue'
    - title: '主題'
      children:
        - '/theme/sidebar'
    - title: '進階'
      children:
        - '/advanced/frontmatter'
        - '/advanced/permalinks'
        - '/advanced/markdown-slot'
  # sidebarDepth: 1
  displayAllHeaders: false
