---
title: Hello Vincent's VuePress
description: Just playing around

base: /vuepress/

markdown:
  lineNumbers: true

themeConfig:
  sidebar:
    # - '/'
    # - 
    #   - '/test'
    #   - 'test page'
    - title: '入門'
      children:
        - '/quick-start'
        - '/config'
        - '/markdown'
        - '/theme'
        - '/deploy'
        # - '/vue'
  # sidebarDepth: 1
  displayAllHeaders: false
